---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: common-labels
labels:
  app.giantswarm.io/branch: '{{ .Values.project.branch }}'
  app.giantswarm.io/commit: '{{ .Values.project.commit }}'
  app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
  helm.sh/chart: gcp-compute-persistent-disk-csi-driver
  app.kubernetes.io/name: gcp-compute-persistent-disk-csi-driver
  app.kubernetes.io/instance: '{{ .Release.Name }}'
fieldSpecs:
  - path: metadata/labels
    create: true
