apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-gce-pd-controller
spec:
  template:
    spec:
      containers:
        - name: gce-pd-driver
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              $patch: delete
          volumeMounts:
            - mountPath: /etc/cloud-sa
              name: cloud-sa-volume
              readOnly: true
              $patch: delete
      volumes:
        - name: cloud-sa-volume
          $patch: delete
          secret:
            secretName: cloud-sa
