---
$patch: delete
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: csi-gce-pd-node-psp-win
---
$patch: delete
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-gce-pd-node-sa-win
---
$patch: delete
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-gce-pd-node-deploy-win
---
$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-gce-pd-node-win
