---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: workload-identity-label
labels:
  giantswarm.io/gcp-workload-identity: "enabled"
fieldSpecs:
  - path: spec/selector/matchLabels
    create: true
    kind: Deployment
  - path: spec/template/metadata
    create: true
    kind: Deployment
