---
apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: workload-identity-annotation
annotations:
  giantswarm.io/gcp-workload-identity-pool-id: '{{.Values.gcpProject}}.svc.id.goog'
fieldSpecs:
  - path: metadata/annotations
    create: true
    version: v1
    kind: ServiceAccount
