apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: cluster-api
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: cluster-api
  name: csi-gce-pd-node-psp-win
spec:
  allowedHostPaths:
  - pathPrefix: \var\lib\kubelet
  - pathPrefix: \var\lib\kubelet\plugins_registry
  - pathPrefix: \var\lib\kubelet\plugins\pd.csi.storage.gke.io
  - pathPrefix: \\.\pipe\csi-proxy-disk-v1
  - pathPrefix: \\.\pipe\csi-proxy-volume-v1
  - pathPrefix: \\.\pipe\csi-proxy-filesystem-v1
  - pathPrefix: \\.\pipe\csi-proxy-disk-v1beta2
  - pathPrefix: \\.\pipe\csi-proxy-volume-v1beta1
  - pathPrefix: \\.\pipe\csi-proxy-filesystem-v1beta1
  fsGroup:
    rule: RunAsAny
  hostNetwork: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
