apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: gcp-compute-persistent-disk-csi-driver
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: gcp-compute-persistent-disk-csi-driver
  name: ssd
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: pd-ssd
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
