apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: cluster-api
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: cluster-api
  name: pd.csi.storage.gke.io
spec:
  attachRequired: true
  podInfoOnMount: false
