apiVersion: v1
stringData:
  credentials: |-
    {{ .Values.gcp.credentials | b64dec | nindent 4 }}
kind: Secret
metadata:
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: gcp-compute-persistent-disk-csi-driver
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: gcp-compute-persistent-disk-csi-driver
  name: cloud-sa
  namespace: '{{ .Release.Namespace }}'
