apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    giantswarm.io/gcp-workload-identity-pool-id: '{{.Values.workloadIdentityPoolId}}'
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: gcp-compute-persistent-disk-csi-driver
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: gcp-compute-persistent-disk-csi-driver
  name: csi-gce-pd-node-sa
  namespace: '{{ .Release.Namespace }}'
