# Please make sure your name DOES NOT end in "app" or "-app".
name: gcp-compute-persistent-disk-csi-driver
version: [[ .Version ]]

# Please describe what the app provides in a sentence or two.
description: The Google Compute Engine Persistent Disk (GCE PD) Container Storage Interface (CSI) Storage Plugin.
appVersion: "[[ .AppVersion ]]"
home: https://github.com/giantswarm/gcp-compute-persistent-disk-csi-driver-app
apiVersion: v1

annotations:
  application.giantswarm.io/team: "hydra"
  config.giantswarm.io/version: 1.x.x

sources:
- https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver

icon: https://s.giantswarm.io/app-icons/gcp/1/light.svg
