name: gcp-compute-persistent-disk-csi-driver
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/gcp-compute-persistent-disk-csi-driver
  tag: v0.0.1
  pullPolicy: IfNotPresent
