version: 2.1
orbs:
  architect: giantswarm/architect@4.31.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          name: "package and push gcp-compute-persistent-disk-csi-driver-app chart"
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "gcp-compute-persistent-disk-csi-driver"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
